Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Click WheelDown
Sleep, 1000
Click 678, 699
Click 678, 421
Sleep, 1000
Send, {enter}